# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Model/GameLayout.h \
    ./Model/ColorUtils.h \
    ./Controller/BlockFillEngine.h \
    ./Model/Coordination/CoordinationConstants.h \
    ./Controller/CoordinationEngine.h \
    ./Model/Coordination/CoordinationTile.h \
    ./Model/BlockFill/BlockFillShape.h \
    ./Model/BlockFill/BlockFillTile.h \
    ./Model/BlockFill/BlockFillConstants.h \
    ./Model/BlockSlide/BlockSlideConstants.h \
    ./Model/BlockSlide/SlidingBlock.h \
    ./Controller/PuzzleSelectGameEngine.h \
    ./Model/TileUtils.h \
    ./Model/TutorialConstants.h \
    ./Controller/BlockSlideEngine.h \
    ./Model/BlockSlide/BlockSlideTile.h \
    ./Controller/FillSquaresEngine.h \
    ./Model/FillTheSquares/FillSquaresTile.h \
    ./Model/FillTheSquares/FillSquareConstants.h \
    ./Model/Battleship/BattleshipShip.h \
    ./Model/Battleship/BattleshipTile.h \
    ./Model/ColorConstants.h \
    ./Model/Minesweeper/MinesweeperTile.h \
    ./Model/ArrayUtils.h \
    ./Controller/PuzzleGames.h \
    ./Model/TutorialDialog.h \
    ./Controller/BattleshipEngine.h \
    ./Controller/GameEngine.h \
    ./Controller/MinesweeperEngine.h \
    ./Model/QDifferentClicksButton.h
SOURCES += ./Model/GameLayout.cpp \
    ./Model/ColorUtils.cpp \
    ./Controller/BlockFillEngine.cpp \
    ./Model/Coordination/CoordinationConstants.cpp \
    ./Controller/CoordinationEngine.cpp \
    ./Model/Coordination/CoordinationTile.cpp \
    ./Model/BlockFill/BlockFillShape.cpp \
    ./Model/BlockFill/BlockFillTile.cpp \
    ./Model/BlockFill/BlockFillConstants.cpp \
    ./Model/BlockSlide/BlockSlideConstants.cpp \
    ./Controller/BlockSlideEngine.cpp \
    ./Model/BlockSlide/BlockSlideTile.cpp \
    ./Controller/BattleshipEngine.cpp \
    ./Controller/FillSquaresEngine.cpp \
    ./Model/FillTheSquares/FillSquaresTile.cpp \
    ./Model/FillTheSquares/FillSquareConstants.cpp \
    ./Model/Battleship/BattleshipShip.cpp \
    ./Model/Battleship/BattleshipTile.cpp \
    ./Model/QDifferentClicks.cpp \
    ./Model/ArrayUtils.cpp \
    ./Model/BlockSlide/SlidingBlock.cpp \
    ./Controller/PuzzleSelectGameEngine.cpp \
    ./Model/TileUtils.cpp \
    ./Model/TutorialDialog.cpp \
    ./Model/TutorialConstants.cpp \
    ./Model/ColorConstants.cpp \
    ./Controller/GameEngine.cpp \
    ./Controller/MinesweeperEngine.cpp \
    ./Model/Minesweeper/MinesweeperTile.cpp \
    ./Controller/PuzzleGames.cpp \
    ./Controller/main.cpp
FORMS += ./View/TutorialDialog.ui \
    ./View/PuzzleGames.ui
RESOURCES += View/PuzzleGames.qrc
